### ISSUE TITLE
Sugestão dependências

### ISSUE THREAD

**Issue by rafaelfaustini** [NatanaelAntonioli/PiramidesCopaDoMundo#2]
Primeiramente parabéns pelo projeto, muito massa (Tanto canal quanto o repositório). 
Tenho uma sugestão quanto as dependências, vi que usou uma biblioteca e sugeriu no vídeo dar um pip install, contudo isso pode gerar problemas no futuro tendo em vista que a biblioteca pode atualizar e quebrar o script. Sugiro uma prática muito comum que é gerar um arquivo `requirements.txt` na pasta do projeto, basta executar o seguinte comando:
`pip freeze > requirements.txt`

Com o `requirements.txt` as pessoas que forem mexer no projeto podem usar o seguinte comando:
`pip install -r requirements.txt`
Com isso o pip instalará as bibliotecas na exata versão que você fez o freeze e que o projeto estava funcionando :)

**Comment by NatanaelAntonioli** [comment]
Perdão pela demora em retornar, e valeu pela sugestão! Inclúi ao projeto.
